/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Irrigations: () => import('#controllers/irrigations_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Pivots: () => import('#controllers/pivots_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
